// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1603231093);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1603231197);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1603231121);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1603231213);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1603231123);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1639);
user_pref("browser.cache.disk.capacity", 296960);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1603231063);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0938b77b-4e4c-4783-b8c1-60f7dd1b4d21}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1603231071");
user_pref("browser.slowStartup.averageTime", 13064);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200720193547");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1603231068);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1603231120832");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "ad0376551443425c896ef657a1a33ac6");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"5d182bc9-74f5-4a20-85c5-78495549be9d\",\"formautofill@mozilla.org\":\"33d24f3b-9f75-4bf3-95dc-7a3769e1e122\",\"screenshots@mozilla.org\":\"9a0f6575-60c2-4276-9a42-48afb8e73d9a\",\"webcompat-reporter@mozilla.org\":\"814cbe25-5613-42f8-9f45-b812468c9f4d\",\"webcompat@mozilla.org\":\"0f6b5a28-20cc-4749-b69e-fcc55114d001\",\"default-theme@mozilla.org\":\"1d0d2d22-6d33-4fb9-a0bb-34d8e21eb097\",\"google@search.mozilla.org\":\"3e5507d5-e85f-4b47-a228-4d54bdc33fc2\",\"amazondotcom@search.mozilla.org\":\"8e19876c-41ef-42c7-8708-33a2690253ec\",\"wikipedia@search.mozilla.org\":\"24fe5cfd-6ecd-4664-a84c-be5baedb12a7\",\"bing@search.mozilla.org\":\"05fbe0e3-5cdf-4cff-8c73-a4409f24ba66\",\"ddg@search.mozilla.org\":\"374cb1a0-ff54-48f3-9972-f8b9945220c4\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-manager.buildID", "20200720193547");
user_pref("media.gmp-manager.lastCheck", 1603231125);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 71883);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "04f58405-be1c-46a0-988a-1fd11ad98dc7");
user_pref("security.sandbox.plugin.tempDirSuffix", "fadc45cb-87e4-486c-adab-78fe241b1e0f");
user_pref("toolkit.startup.last_success", 1603231056);
user_pref("toolkit.telemetry.cachedClientID", "e671952c-edfc-493a-973b-f09908bfd6a0");
user_pref("toolkit.telemetry.previousBuildID", "20200720193547");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
